service: alexa-sonos-intercom-skill


provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  region: us-east-1
  timeout: 10
  versionFunctions: true


functions:
  message:
    handler: handler.message
    environment:
      SONOS_API_SERVER: ${env:SONOS_API_SERVER}
      AUTH_USERNAME: ${env:AUTH_USERNAME}
      AUTH_PASSWORD: ${env:AUTH_PASSWORD}
    events:
      - alexaSkill
